"""message

Revision ID: 34a07f3e8ab1
Revises: 7562179d6e8d
Create Date: 2026-05-17 13:45:28.512570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a07f3e8ab1'
down_revision: Union[str, Sequence[str], None] = '7562179d6e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_activity_logs_actor_created_at'), table_name='activity_logs')
    op.drop_index(op.f('idx_activity_logs_event_type'), table_name='activity_logs')
    op.drop_index(op.f('idx_activity_logs_project_created_at'), table_name='activity_logs')
    op.drop_index(op.f('idx_activity_logs_task_id'), table_name='activity_logs')
    op.create_index(op.f('ix_activity_logs_actor_id'), 'activity_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_event_type'), 'activity_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_project_id'), 'activity_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_task_id'), 'activity_logs', ['task_id'], unique=False)
    op.alter_column('admin_logs', 'log_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_admin_logs_admin_id'), table_name='admin_logs')
    op.drop_index(op.f('idx_admin_logs_created_at'), table_name='admin_logs')
    op.drop_index(op.f('idx_admin_logs_target_user_id'), table_name='admin_logs')
    op.create_index(op.f('ix_admin_logs_admin_id'), 'admin_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_logs_created_at'), 'admin_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_logs_target_user_id'), 'admin_logs', ['target_user_id'], unique=False)
    op.alter_column('ai_plans', 'plan_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ai_plans', 'generated_by',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('idx_ai_plans_created_at'), table_name='ai_plans')
    op.drop_index(op.f('idx_ai_plans_generated_by'), table_name='ai_plans')
    op.drop_index(op.f('idx_ai_plans_project_id'), table_name='ai_plans')
    op.create_index(op.f('ix_ai_plans_created_at'), 'ai_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_plans_generated_by'), 'ai_plans', ['generated_by'], unique=False)
    op.create_index(op.f('ix_ai_plans_project_id'), 'ai_plans', ['project_id'], unique=False)
    op.drop_constraint(op.f('fk_ai_plans_generated_by'), 'ai_plans', type_='foreignkey')
    op.create_foreign_key(None, 'ai_plans', 'users', ['generated_by'], ['user_id'], ondelete='SET NULL')
    op.alter_column('attachments', 'attachment_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_attachments_project_id'), table_name='attachments')
    op.drop_index(op.f('idx_attachments_task_id'), table_name='attachments')
    op.drop_index(op.f('idx_attachments_uploaded_by'), table_name='attachments')
    op.create_index(op.f('ix_attachments_project_id'), 'attachments', ['project_id'], unique=False)
    op.create_index(op.f('ix_attachments_task_id'), 'attachments', ['task_id'], unique=False)
    op.create_index(op.f('ix_attachments_uploaded_by'), 'attachments', ['uploaded_by'], unique=False)
    op.drop_constraint(op.f('fk_attachments_task_project'), 'attachments', type_='foreignkey')
    op.create_foreign_key(None, 'attachments', 'tasks', ['task_id'], ['task_id'], ondelete='SET NULL')
    op.alter_column('chat_messages', 'message_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_chat_messages_project_created'), table_name='chat_messages')
    op.drop_index(op.f('idx_chat_messages_project_id'), table_name='chat_messages')
    op.drop_index(op.f('idx_chat_messages_sender'), table_name='chat_messages')
    op.drop_index(op.f('idx_chat_messages_sender_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_project_id'), 'chat_messages', ['project_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False)
    op.drop_constraint(op.f('fk_chat_messages_sender'), 'chat_messages', type_='foreignkey')
    op.alter_column('comment_mentions', 'mention_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_comment_mentions_comment'), table_name='comment_mentions')
    op.drop_index(op.f('idx_comment_mentions_mentioned_by'), table_name='comment_mentions')
    op.drop_index(op.f('idx_comment_mentions_mentioned_user'), table_name='comment_mentions')
    op.drop_index(op.f('idx_comment_mentions_project'), table_name='comment_mentions')
    op.drop_index(op.f('idx_comment_mentions_task'), table_name='comment_mentions')
    op.create_index(op.f('ix_comment_mentions_comment_id'), 'comment_mentions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_mentions_mentioned_by'), 'comment_mentions', ['mentioned_by'], unique=False)
    op.create_index(op.f('ix_comment_mentions_mentioned_user_id'), 'comment_mentions', ['mentioned_user_id'], unique=False)
    op.create_index(op.f('ix_comment_mentions_project_id'), 'comment_mentions', ['project_id'], unique=False)
    op.create_index(op.f('ix_comment_mentions_task_id'), 'comment_mentions', ['task_id'], unique=False)
    op.alter_column('comments', 'comment_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_comments_task_created_at'), table_name='comments')
    op.drop_index(op.f('idx_comments_task_id'), table_name='comments')
    op.drop_index(op.f('idx_comments_user_id'), table_name='comments')
    op.create_index(op.f('ix_comments_task_id'), 'comments', ['task_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_comments_user'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('deadline_reminders', 'reminder_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_deadline_reminders_generated_at'), table_name='deadline_reminders')
    op.drop_index(op.f('idx_deadline_reminders_project'), table_name='deadline_reminders')
    op.drop_index(op.f('idx_deadline_reminders_task'), table_name='deadline_reminders')
    op.drop_index(op.f('idx_deadline_reminders_type'), table_name='deadline_reminders')
    op.drop_index(op.f('idx_deadline_reminders_user'), table_name='deadline_reminders')
    op.create_index(op.f('ix_deadline_reminders_project_id'), 'deadline_reminders', ['project_id'], unique=False)
    op.create_index(op.f('ix_deadline_reminders_reminder_type'), 'deadline_reminders', ['reminder_type'], unique=False)
    op.create_index(op.f('ix_deadline_reminders_task_id'), 'deadline_reminders', ['task_id'], unique=False)
    op.create_index(op.f('ix_deadline_reminders_user_id'), 'deadline_reminders', ['user_id'], unique=False)
    op.drop_index(op.f('idx_device_tokens_active_by_user'), table_name='device_tokens', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_device_tokens_user_id'), table_name='device_tokens')
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.alter_column('email_verification_codes', 'verification_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_email_verification_codes_user_id'), table_name='email_verification_codes')
    op.alter_column('invitations', 'invitation_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_invitations_email_status'), table_name='invitations')
    op.drop_index(op.f('idx_invitations_invited_user_status'), table_name='invitations')
    op.drop_index(op.f('idx_invitations_project_id'), table_name='invitations')
    op.drop_index(op.f('idx_invitations_status_expires_at'), table_name='invitations')
    op.drop_index(op.f('idx_invitations_team_id'), table_name='invitations')
    op.drop_index(op.f('uq_pending_project_invitation_email'), table_name='invitations', postgresql_where="(((status)::text = 'pending'::text) AND (project_id IS NOT NULL) AND (email IS NOT NULL))")
    op.drop_index(op.f('uq_pending_project_invitation_user'), table_name='invitations', postgresql_where="(((status)::text = 'pending'::text) AND (project_id IS NOT NULL) AND (invited_user_id IS NOT NULL))")
    op.drop_index(op.f('uq_pending_team_invitation_email'), table_name='invitations', postgresql_where="(((status)::text = 'pending'::text) AND (project_id IS NULL) AND (email IS NOT NULL))")
    op.drop_index(op.f('uq_pending_team_invitation_user'), table_name='invitations', postgresql_where="(((status)::text = 'pending'::text) AND (project_id IS NULL) AND (invited_user_id IS NOT NULL))")
    op.create_index(op.f('ix_invitations_invited_by'), 'invitations', ['invited_by'], unique=False)
    op.create_index(op.f('ix_invitations_invited_user_id'), 'invitations', ['invited_user_id'], unique=False)
    op.create_index(op.f('ix_invitations_project_id'), 'invitations', ['project_id'], unique=False)
    op.create_index(op.f('ix_invitations_team_id'), 'invitations', ['team_id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.alter_column('notifications', 'notification_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.drop_index(op.f('idx_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_unread_by_user'), table_name='notifications', postgresql_where='(is_read = false)')
    op.drop_index(op.f('idx_notifications_user_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('oauth_accounts', 'oauth_account_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('password_reset_codes', 'reset_code_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_password_reset_codes_user_id'), table_name='password_reset_codes')
    op.alter_column('project_members', 'member_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_project_members_user_id'), table_name='project_members')
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.alter_column('projects', 'project_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_projects_created_by'), table_name='projects')
    op.drop_index(op.f('idx_projects_status'), table_name='projects')
    op.drop_index(op.f('idx_projects_team_id'), table_name='projects')
    op.create_index(op.f('ix_projects_created_by'), 'projects', ['created_by'], unique=False)
    op.create_index(op.f('ix_projects_team_id'), 'projects', ['team_id'], unique=False)
    op.drop_constraint(op.f('fk_projects_team'), 'projects', type_='foreignkey')
    op.alter_column('risk_analysis', 'risk_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('risk_analysis', 'predicted_delay_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('risk_analysis', 'reason',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('risk_analysis', 'recommendation',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('idx_risk_analysis_project_id'), table_name='risk_analysis')
    op.create_index(op.f('ix_risk_analysis_created_at'), 'risk_analysis', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_analysis_project_id'), 'risk_analysis', ['project_id'], unique=False)
    op.create_index(op.f('ix_risk_analysis_risk_level'), 'risk_analysis', ['risk_level'], unique=False)
    op.drop_index(op.f('idx_smart_schedules_created_at'), table_name='smart_schedules')
    op.drop_index(op.f('idx_smart_schedules_generated_by'), table_name='smart_schedules')
    op.drop_index(op.f('idx_smart_schedules_project_id'), table_name='smart_schedules')
    op.create_index(op.f('ix_smart_schedules_created_at'), 'smart_schedules', ['created_at'], unique=False)
    op.create_index(op.f('ix_smart_schedules_generated_by'), 'smart_schedules', ['generated_by'], unique=False)
    op.create_index(op.f('ix_smart_schedules_project_id'), 'smart_schedules', ['project_id'], unique=False)
    op.alter_column('tasks', 'task_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tasks', 'estimated_hours',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=None,
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)
    op.alter_column('tasks', 'actual_hours',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=None,
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('idx_tasks_assigned_to'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_created_by'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    op.drop_constraint(op.f('uq_tasks_project'), 'tasks', type_='unique')
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_created_by'), 'tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.alter_column('team_members', 'team_member_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_team_members_user_id'), table_name='team_members')
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.alter_column('teams', 'team_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=False)
    op.drop_index(op.f('idx_teams_created_by'), table_name='teams')
    op.create_index(op.f('ix_teams_created_by'), 'teams', ['created_by'], unique=False)
    op.alter_column('user_progress', 'progress_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_user_progress_project'), table_name='user_progress')
    op.drop_index(op.f('idx_user_progress_project_id'), table_name='user_progress')
    op.drop_index(op.f('idx_user_progress_user'), table_name='user_progress')
    op.drop_index(op.f('idx_user_progress_user_id'), table_name='user_progress')
    op.create_index(op.f('ix_user_progress_project_id'), 'user_progress', ['project_id'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.alter_column('users', 'user_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_project_id'), table_name='user_progress')
    op.create_index(op.f('idx_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_progress_user'), 'user_progress', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_progress_project_id'), 'user_progress', ['project_id'], unique=False)
    op.create_index(op.f('idx_user_progress_project'), 'user_progress', ['project_id'], unique=False)
    op.alter_column('user_progress', 'progress_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_teams_created_by'), table_name='teams')
    op.create_index(op.f('idx_teams_created_by'), 'teams', ['created_by'], unique=False)
    op.alter_column('teams', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('teams', 'team_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.create_index(op.f('idx_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.alter_column('team_members', 'team_member_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.create_unique_constraint(op.f('uq_tasks_project'), 'tasks', ['task_id', 'project_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('idx_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('idx_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('idx_tasks_created_by'), 'tasks', ['created_by'], unique=False)
    op.create_index(op.f('idx_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.alter_column('tasks', 'actual_hours',
               existing_type=sa.Numeric(precision=8, scale=2),
               server_default=sa.text('0'),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('tasks', 'estimated_hours',
               existing_type=sa.Numeric(precision=8, scale=2),
               server_default=sa.text('0'),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('tasks', 'task_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_smart_schedules_project_id'), table_name='smart_schedules')
    op.drop_index(op.f('ix_smart_schedules_generated_by'), table_name='smart_schedules')
    op.drop_index(op.f('ix_smart_schedules_created_at'), table_name='smart_schedules')
    op.create_index(op.f('idx_smart_schedules_project_id'), 'smart_schedules', ['project_id'], unique=False)
    op.create_index(op.f('idx_smart_schedules_generated_by'), 'smart_schedules', ['generated_by'], unique=False)
    op.create_index(op.f('idx_smart_schedules_created_at'), 'smart_schedules', ['created_at'], unique=False)
    op.drop_index(op.f('ix_risk_analysis_risk_level'), table_name='risk_analysis')
    op.drop_index(op.f('ix_risk_analysis_project_id'), table_name='risk_analysis')
    op.drop_index(op.f('ix_risk_analysis_created_at'), table_name='risk_analysis')
    op.create_index(op.f('idx_risk_analysis_project_id'), 'risk_analysis', ['project_id'], unique=False)
    op.alter_column('risk_analysis', 'recommendation',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('risk_analysis', 'reason',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('risk_analysis', 'predicted_delay_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('risk_analysis', 'risk_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_foreign_key(op.f('fk_projects_team'), 'projects', 'teams', ['team_id'], ['team_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_projects_team_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_by'), table_name='projects')
    op.create_index(op.f('idx_projects_team_id'), 'projects', ['team_id'], unique=False)
    op.create_index(op.f('idx_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('idx_projects_created_by'), 'projects', ['created_by'], unique=False)
    op.alter_column('projects', 'project_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.create_index(op.f('idx_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.alter_column('project_members', 'member_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('idx_password_reset_codes_user_id'), 'password_reset_codes', ['user_id'], unique=False)
    op.alter_column('password_reset_codes', 'reset_code_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('oauth_accounts', 'oauth_account_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_unread_by_user'), 'notifications', ['user_id'], unique=False, postgresql_where='(is_read = false)')
    op.create_index(op.f('idx_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('notifications', 'notification_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_invitations_team_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_project_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_invited_user_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_invited_by'), table_name='invitations')
    op.create_index(op.f('uq_pending_team_invitation_user'), 'invitations', ['team_id', 'invited_user_id'], unique=True, postgresql_where="(((status)::text = 'pending'::text) AND (project_id IS NULL) AND (invited_user_id IS NOT NULL))")
    op.create_index(op.f('uq_pending_team_invitation_email'), 'invitations', ['team_id', sa.literal_column('lower(email::text)')], unique=True, postgresql_where="(((status)::text = 'pending'::text) AND (project_id IS NULL) AND (email IS NOT NULL))")
    op.create_index(op.f('uq_pending_project_invitation_user'), 'invitations', ['project_id', 'invited_user_id'], unique=True, postgresql_where="(((status)::text = 'pending'::text) AND (project_id IS NOT NULL) AND (invited_user_id IS NOT NULL))")
    op.create_index(op.f('uq_pending_project_invitation_email'), 'invitations', ['project_id', sa.literal_column('lower(email::text)')], unique=True, postgresql_where="(((status)::text = 'pending'::text) AND (project_id IS NOT NULL) AND (email IS NOT NULL))")
    op.create_index(op.f('idx_invitations_team_id'), 'invitations', ['team_id'], unique=False)
    op.create_index(op.f('idx_invitations_status_expires_at'), 'invitations', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('idx_invitations_project_id'), 'invitations', ['project_id'], unique=False)
    op.create_index(op.f('idx_invitations_invited_user_status'), 'invitations', ['invited_user_id', 'status'], unique=False)
    op.create_index(op.f('idx_invitations_email_status'), 'invitations', ['email', 'status'], unique=False)
    op.alter_column('invitations', 'invitation_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('idx_email_verification_codes_user_id'), 'email_verification_codes', ['user_id'], unique=False)
    op.alter_column('email_verification_codes', 'verification_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.create_index(op.f('idx_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_device_tokens_active_by_user'), 'device_tokens', ['user_id'], unique=False, postgresql_where='(is_active = true)')
    op.drop_index(op.f('ix_deadline_reminders_user_id'), table_name='deadline_reminders')
    op.drop_index(op.f('ix_deadline_reminders_task_id'), table_name='deadline_reminders')
    op.drop_index(op.f('ix_deadline_reminders_reminder_type'), table_name='deadline_reminders')
    op.drop_index(op.f('ix_deadline_reminders_project_id'), table_name='deadline_reminders')
    op.create_index(op.f('idx_deadline_reminders_user'), 'deadline_reminders', ['user_id'], unique=False)
    op.create_index(op.f('idx_deadline_reminders_type'), 'deadline_reminders', ['reminder_type'], unique=False)
    op.create_index(op.f('idx_deadline_reminders_task'), 'deadline_reminders', ['task_id'], unique=False)
    op.create_index(op.f('idx_deadline_reminders_project'), 'deadline_reminders', ['project_id'], unique=False)
    op.create_index(op.f('idx_deadline_reminders_generated_at'), 'deadline_reminders', ['generated_at'], unique=False)
    op.alter_column('deadline_reminders', 'reminder_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comments_user'), 'comments', 'users', ['user_id'], ['user_id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_task_id'), table_name='comments')
    op.create_index(op.f('idx_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_index(op.f('idx_comments_task_id'), 'comments', ['task_id'], unique=False)
    op.create_index(op.f('idx_comments_task_created_at'), 'comments', ['task_id', 'created_at'], unique=False)
    op.alter_column('comments', 'comment_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_comment_mentions_task_id'), table_name='comment_mentions')
    op.drop_index(op.f('ix_comment_mentions_project_id'), table_name='comment_mentions')
    op.drop_index(op.f('ix_comment_mentions_mentioned_user_id'), table_name='comment_mentions')
    op.drop_index(op.f('ix_comment_mentions_mentioned_by'), table_name='comment_mentions')
    op.drop_index(op.f('ix_comment_mentions_comment_id'), table_name='comment_mentions')
    op.create_index(op.f('idx_comment_mentions_task'), 'comment_mentions', ['task_id'], unique=False)
    op.create_index(op.f('idx_comment_mentions_project'), 'comment_mentions', ['project_id'], unique=False)
    op.create_index(op.f('idx_comment_mentions_mentioned_user'), 'comment_mentions', ['mentioned_user_id'], unique=False)
    op.create_index(op.f('idx_comment_mentions_mentioned_by'), 'comment_mentions', ['mentioned_by'], unique=False)
    op.create_index(op.f('idx_comment_mentions_comment'), 'comment_mentions', ['comment_id'], unique=False)
    op.alter_column('comment_mentions', 'mention_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_foreign_key(op.f('fk_chat_messages_sender'), 'chat_messages', 'users', ['sender_id'], ['user_id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_chat_messages_sender_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_project_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.create_index(op.f('idx_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False)
    op.create_index(op.f('idx_chat_messages_sender'), 'chat_messages', ['sender_id'], unique=False)
    op.create_index(op.f('idx_chat_messages_project_id'), 'chat_messages', ['project_id'], unique=False)
    op.create_index(op.f('idx_chat_messages_project_created'), 'chat_messages', ['project_id', 'created_at'], unique=False)
    op.alter_column('chat_messages', 'message_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_attachments_task_project'), 'attachments', 'tasks', ['task_id', 'project_id'], ['task_id', 'project_id'], ondelete='SET NULL (task_id)')
    op.drop_index(op.f('ix_attachments_uploaded_by'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_task_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_project_id'), table_name='attachments')
    op.create_index(op.f('idx_attachments_uploaded_by'), 'attachments', ['uploaded_by'], unique=False)
    op.create_index(op.f('idx_attachments_task_id'), 'attachments', ['task_id'], unique=False)
    op.create_index(op.f('idx_attachments_project_id'), 'attachments', ['project_id'], unique=False)
    op.alter_column('attachments', 'attachment_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'ai_plans', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ai_plans_generated_by'), 'ai_plans', 'users', ['generated_by'], ['user_id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_ai_plans_project_id'), table_name='ai_plans')
    op.drop_index(op.f('ix_ai_plans_generated_by'), table_name='ai_plans')
    op.drop_index(op.f('ix_ai_plans_created_at'), table_name='ai_plans')
    op.create_index(op.f('idx_ai_plans_project_id'), 'ai_plans', ['project_id'], unique=False)
    op.create_index(op.f('idx_ai_plans_generated_by'), 'ai_plans', ['generated_by'], unique=False)
    op.create_index(op.f('idx_ai_plans_created_at'), 'ai_plans', ['created_at'], unique=False)
    op.alter_column('ai_plans', 'generated_by',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('ai_plans', 'plan_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_admin_logs_target_user_id'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_created_at'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_admin_id'), table_name='admin_logs')
    op.create_index(op.f('idx_admin_logs_target_user_id'), 'admin_logs', ['target_user_id'], unique=False)
    op.create_index(op.f('idx_admin_logs_created_at'), 'admin_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_admin_logs_admin_id'), 'admin_logs', ['admin_id'], unique=False)
    op.alter_column('admin_logs', 'log_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_activity_logs_task_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_project_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_event_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_actor_id'), table_name='activity_logs')
    op.create_index(op.f('idx_activity_logs_task_id'), 'activity_logs', ['task_id'], unique=False)
    op.create_index(op.f('idx_activity_logs_project_created_at'), 'activity_logs', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_activity_logs_event_type'), 'activity_logs', ['event_type'], unique=False)
    op.create_index(op.f('idx_activity_logs_actor_created_at'), 'activity_logs', ['actor_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
